# Easy way to generate all the State Level YoY Comp charts and allows new charts to be quickly added
metrics:
  - name: 'Housing Units per Capita'
    details:
      label: 'Housing Units per Capita'
      y_format: ',.3f'
      variable: None
      rate_flag: 1
      numerator: 'B25001_001E'
      denominator: 'B01003_001E'
  - name: 'Vacancy Rate'
    details:
      label: 'Vacancy Rate'
      y_format: '.1%'
      variable: None
      rate_flag: 1
      numerator: 'B25002_003E'
      denominator: 'B25002_001E'
  - name: 'Median Household Income'
    details:
      label: 'Median Household Income'
      y_format: '$,.0f'
      variable: 'B19013_001E'
      rate_flag: None
      numerator: None
      denominator: None
  - name: 'Median Household Income -- Renters'
    details:
      label: 'Median Household Income -- Renters'
      y_format: '$,.0f'
      variable: 'B25119_003E'
      rate_flag: None
      numerator: None
      denominator: None
  - name: 'Median Contract Rent'
    details:
      label: 'Median Contract Rent'
      y_format: '$,.0f'
      variable: 'B25058_001E'
      rate_flag: None
      numerator: None
      denominator: None
  - name: 'Median Household Income -- Owners'
    details:
      label: 'Median Household Income -- Owners'
      y_format: '$,.0f'
      variable: 'B25119_002E'
      rate_flag: None
      numerator: None
      denominator: None
  - name: 'Median Home Value'
    details:
      label: 'Median Home Value'
      y_format: '$,.0f'
      variable: 'B25077_001E'
      rate_flag: None
      numerator: None
      denominator: None
  - name: 'Homeownership Rate'
    details:
      label: 'Homeownership Rate'
      y_format: '.0%'
      variable: None
      rate_flag: 1
      numerator: 'B25003_002E'
      denominator: 'B25003_001E'
  - name: 'Home Value to Income Ratio'
    details:
      label: 'Home Value to Income Ratio'
      y_format: ',.1f'
      variable: None
      rate_flag: 1
      numerator: 'B25077_001E'
      denominator: 'B19013_001E'
  - name: 'Contract Rent to Income Ratio'
    details:
      label: 'Contract Rent to Income Ratio'
      y_format: ',.3f'
      variable: None
      rate_flag: 1
      numerator: 'B25058_001E'
      denominator: 'B19013_001E'
  - name: 'Poverty Rate'
    details:
      label: 'Poverty Rate'
      y_format: '.0%'
      variable: None
      rate_flag: 1
      numerator: 'B05010_002E'
      denominator: 'B05010_001E'