[theme]
primaryColor="#c3002f"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"


#default
#[theme]
#primaryColor="#FF4B4B"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#31333F"